### ISSUE TITLE
Facing issue launching emulator with Mac Mini machines with Graphics card Intel 4000

### ISSUE THREAD

**Issue by anallur** [quittle/gradle-android-emulator#115]
We are trying to run the  waitForAndroidEmulator task in these machines and emulator closes as soon as the emulator is launched.

The emulators created from AVD works fine, however the emulators created from the plugin provide GPU error, as below

Your GPU driver information:

GPU #1
Make: 8086
Model: Intel(R) HD Graphics Family
Device ID: 0a16
Driver version: 10.18.10.3945

Some users have experienced emulator stability issues with this driver version. As a result, we are selecting a compatibility renderer. Please check with your manufacturer to see if there is an updated driver available. 

Is there a way we can only run the emulator that is present in avd manager only?

**Comment by quittle** [comment]
Hi, sorry for the delayed response. Are you configuring the emulator generated by the plugin? By default it specifies minimal configuration to the CLI so if you are checking boxes when creating your emulator through the GUI, I recommend figuring out what the equivalents are in the CLI and specifying them in the `androidEmulator` configuration of your `buile.gradle`. If you are already doing that, then could you send me the configuration you are specifying and what flags you think are being missed that would get the emulator working on your device?

**Comment by quittle** [comment]
Hey @anallur, did my suggestion work for you?

**Comment by anallur** [comment]
Hi @quittle  I tried multiple things. Even tried with the -gpu host for the arguments. There seems to be some issue with that computer. I tried with a Mac mini with a similar configuration, and it worked just fine. It was really a strange issue and i am gonna get that machine reimaged. 

Please close this ticket as we would not be pursuing it further. 

You have done a great job with this plugin.
Can i recommend a feature, to have a flag in the configuration, to just run an existing emulator from the AVD_ROOT folder rather than creating one?

**Comment by quittle** [comment]
> You have done a great job with this plugin.

😊 Aww shucks. Thanks for that.

I never migrated this package to deploy with Github Actions after Travis CI switched to being a paid service with trial credits. Your request is pretty simple so I'll try and add it soon after I get this package deployable again 😛.

**Comment by quittle** [comment]
I have filed your feature request as #118.
