### ISSUE TITLE
Allow automatic detection of abi based on machine it is running on

### ISSUE THREAD

**Issue by dalewking** [quittle/gradle-android-emulator#183]
We are now setting up a Mac Studio as a build machine which of course runs on an ARM chip. The value for abi defaults to x86. It would be nice if there was a way to set abi automatically based on whether the computer it is running on is x86 or ARM.

**Comment by quittle** [comment]
Oh, that's a good idea. I'd be happy to review a PR of this feature but won't have time to work on it personally for at least a month :/

**Comment by dalewking** [comment]
Here is my workaround:
```
fun Project.execWithOutput(spec: ExecSpec.() -> Unit) =
    ByteArrayOutputStream().use { it ->
        exec {
            spec()
            standardOutput = it
        }
        it.toString().trim()
    }

fun determineEmulatorAbi() =
    when (execWithOutput { commandLine("uname", "-m") }) {
        "arm64" -> "arm64-v8a"
        else -> "x86"
    }
```

**Comment by quittle** [comment]
You might be able to simplify it even further by just checking `System.properties['os.arch']` to figure out what system you're on

**Comment by StefanOltmann** [comment]
> You might be able to simplify it even further by just checking `System.properties['os.arch']` to figure out what system you're on

This works in my `build.gradle.kts`:
```
    val arch = System.getProperty("os.arch")

    val abi = if (arch == "aarch64")
        "arm64-v8a"
    else
        "x86_64"
```

**Comment by quittle** [comment]
Completed as part of https://github.com/quittle/gradle-android-emulator/pull/213
