### ISSUE TITLE
This plugin forces version of AGP

### ISSUE THREAD

**Issue by dalewking** [quittle/gradle-android-emulator#187]
We have been dealing with for a long time weirdness in our Android project where the android block in the gradle file showed as one big error and more recent changes in the Android block were not supported. I now understand why.

We were using 0.4.1 of this plugin, which has a hard implementation dependency on version 4.1.0 of the Android gradle plugin which would override anything we told gradle to use.

Shouldn't the dependency on the Android gradle plugin be a runtime only dependency?

**Comment by quittle** [comment]
Interesting, I tried to avoid that but probably messed up the dependency terms from Gradle. I'm a bit busy at the moment but will try to get it in the next month. I'd be happy to review a PR with a fix though if you're willing.

**Comment by dalewking** [comment]
Well part of the reason that got me motivated to get to the bottom of why we were having so much trouble with the android project was that I was trying to switch to the new [Gradle Managed Virtual Devices](https://developer.android.com/studio/preview/features#dolphin-testing) which means we actually won't be using this plugin any more so not terribly motivated myself, but I think all you need to do is switch the dependency declaration from an `implementation` dependency to an `api` dependency.

**Comment by quittle** [comment]
Yeah, that's exciting. I totally want to switch to that when it launches. I remember hearing about Google working on this feature like a year ago but it's been a long while and they still haven't launched it in a stable release yet.

I'll try your suggestion.

**Comment by quittle** [comment]
Hmm, I'm looking into it and it doesn't seem like `com.quittle.setup-android-sdk` has a runtime dependency on the Android Gradle plugin. It uses the `compileOnly` dependency today ([proof from Maven for version `3.0.0`](https://mvnrepository.com/artifact/com.quittle/setup-android-sdk/3.0.0)). I see that the last time this plugin had a runtime dependency on the Android Gradle plugin was version [`1.3.0`](https://mvnrepository.com/artifact/com.quittle/setup-android-sdk/1.3.0). It now only has a runtime dependency on Apache Commons IO.

Thank you for reporting this though. If you can't move to the AGP feature and still have problems, please feel free to re-open or file a new issue.

**Comment by dalewking** [comment]
The managed gradle virtual devices is released

**Comment by dalewking** [comment]
Based on this line of code it is not a compile only dependency, but not sure if it would make a difference:
https://github.com/quittle/gradle-android-emulator/blob/main/android-emulator-plugin/build.gradle#L66

**Comment by quittle** [comment]
You're completely right. I was looking at a different plugin I maintain, 🙃. I'll get on fixing that as it was never my intention to dictate the plugin version brought in by consumers.

**Comment by dalewking** [comment]
> Yeah, that's exciting. I totally want to switch to that when it launches. I remember hearing about Google working on this feature like a year ago but it's been a long while and they still haven't launched it in a stable release yet.

It is in the stable versions of the Android gradle plug-in (we are using 7.2.1) so it isn't as though you have to install an unreleased version. But if you use it does give you a warning that it is an incubating feature but that only means that the syntax may change in the future
