### ISSUE TITLE
How to run custom ADB commands?

### ISSUE THREAD

**Issue by StefanOltmann** [quittle/gradle-android-emulator#193]
I want to run my emulator at level API 31 and use "Shot" to capture screenshots.

Their documentation on https://github.com/pedrovgs/Shot#using-shot-on-api-28 states that I need to run the command `adb shell settings put global hidden_api_policy  1`.

How can I do that using the plugin?

**Comment by quittle** [comment]
You could create a new task in your `build.gradle` that depends on `waitForAndroidEmulator` and has an implementation similar to this plugin's [`WaitForAndroidEmulatorTask`]( https://github.com/quittle/gradle-android-emulator/blob/main/android-emulator-plugin/src/main/java/com/quittle/androidemulator/task/WaitForAndroidEmulatorTask.java). Set up that task similar to

https://github.com/quittle/gradle-android-emulator/blob/d6b74ec86855f53d8bfe6f721778a012403c99c8/android-emulator-plugin/src/main/java/com/quittle/androidemulator/AndroidEmulatorPlugin.java#L24-30

but configure your task to be finalized by the `DeviceProviderInstrumentTestTask` tasks.

**Comment by StefanOltmann** [comment]
Thanks for your answer.

I try to use these dependencies, but it seems I do something wrong.

Maybe it's because I fail to translate the Groovy Gradle samples to Kotlin DSL.

I want to run a task before the Android Emulator stops, but  `finalizedBy(stopAndroidEmulator)` does not the job unfortunately.

This is as far as I got:
```
tasks.register<Exec>("runAndroidTest") {

    /* The test must run first. */
    val connectedCheck by tasks.getting
    dependsOn(connectedCheck)

    val connectedDebugAndroidTest by tasks.getting
    dependsOn(connectedDebugAndroidTest)

    /* Don't stop the emulator until we are done. */
    val stopAndroidEmulator by tasks.getting
    finalizedBy(stopAndroidEmulator)

    doLast {

        val file = File(project.buildDir.absolutePath, "pull_files_from_adb.sh")

        println("Execute $file")

        commandLine("$file")
    }
}
```

But after my unit test fails it runs `stopAndroidEmulator`:
```
> Task :android:connectedDebugAndroidTest FAILED
> Task :android:stopAndroidEmulator
```

In this case I try to copy screenshots made by my tests before the emulator is killed.

**Comment by quittle** [comment]
I'm confused. What you brought up before was trying to run ADB commands prior to the diffs running. The code snippet you sent me seems to be about what to run after the tests run.

I'm confused by your `tasks.getting` since it is a function that should take a class. Assuming you have them set up to retrieve the expected tasks, you should have this final task do two things. It needs to be finalized by stopAndroidEmulator which it seems like you have done correctly. It also needs to run after the tests run. The problem is `connectedCheck` depends on several tasks and is finalized by the stopAndroidEmulator task. What it needs make sure it runs after are the tasks made with the class `DeviceProviderInstrumentTestTask`.

Pseudo-code below
```
val pullFilesTask = ...

tasks.withType(DeviceProviderInstrumentTestTask.class, task -> {
    pullFilesTask.dependsOn(task)
});
pullFilesTask.finalizedBy(stopAndroidEmulator)
```

Also, there's no real difference in your situation if you use `doFirst` or `doLast`. These are just in relationship to the action of the task itself, which for these tasks created in groovy files tend to be no-ops.

**Comment by StefanOltmann** [comment]
Sorry for the confusion.

I actually have both cases: To run something after the emulator started and before the tests begin (`adb shell settings put global hidden_api_policy 1`) as well as run something after the tests are done and before the emulators is stopped (pulling files).

Since you provided me a way for my first use case in your answer I tried to adapt this to my second use case.

**Comment by StefanOltmann** [comment]
Okay, I think I got it. The tasks are not executed in expected order.
Thank you a lot for help!

I added these lines at the end of my `build.gradle.kts`:
```
tasks.register("configureEmulator") {
    // ...
}

tasks.register("pullFilesTask") {
    // ...
}

val configureEmulator: Task by tasks.getting
val pullFilesTask: Task by tasks.getting

// After the emulator got ready we want to configure it
tasks.withType<WaitForAndroidEmulatorTask> {
    this.finalizedBy(configureEmulator)
}

// Tests should not run until the emulator is configured
tasks.withType<com.android.build.gradle.internal.tasks.DeviceProviderInstrumentTestTask> {
    this.dependsOn(configureEmulator)
}

// Finalize test task by pulling the files
tasks.withType<com.android.build.gradle.internal.tasks.DeviceProviderInstrumentTestTask> {
    this.finalizedBy(pullFilesTask)
}

// Before the emulator can stop the files must be pulled first
tasks.withType<StopAndroidEmulatorTask> {
    this.dependsOn(pullFilesTask)
}
```
