### ISSUE TITLE
Does it work with GitHub Actions?

### ISSUE THREAD

**Issue by StefanOltmann** [quittle/gradle-android-emulator#197]
Without further investigating I would like to ask if you know about any issues running it with GitHub Actions.

My integration test runs fine on my local machine and I just tried to execute it with GitHub Actions, but it fails here:
```
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':android:installSdkDependenciesForAndroidEmulatorPlugin'.
> Unable to make android emulator executable
```

**Comment by quittle** [comment]
I was unable to get it to run on GitHub Actions, not because of the issue you faced but because the test runners don't support running emulators. I think they may have a chance of working on the mac runtime but not Linux

**Comment by StefanOltmann** [comment]
Thank you for your quick response. I guess Android Emulators must work, because the GitHub runner has an Android Emulator installed: https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md

I try that manually now and got the error message `PANIC: Avd's CPU Architecture 'arm64' is not supported by the QEMU2 emulator on x86_64 host.`. I used the `arm64-v8a` ABI which is most likely my error.

**Comment by StefanOltmann** [comment]
I guess I just give my vote for https://github.com/quittle/gradle-android-emulator/issues/183 , because since I'm developing on a Mac, but want to run it on a Linux GitHub runner this seems to be my problem.

Of course I could run it on the Mac GitHub runner, but they are really expensive.

**Comment by StefanOltmann** [comment]
> because the test runners don't support running emulators

You are right about that after all. It's installed on the machine for some reason, but it's unusable because it denies to start at all due to missing hardware acceleration.

https://github.com/ReactiveCircus/android-emulator-runner/issues/46

I closed the issue because this problem has nothing to do with your plugin.
Maybe you could see if the log message could be improved to hint to that problem.
