### ISSUE TITLE
How do I use this plugin?

### ISSUE THREAD

**Issue by ParohyGr** [quittle/gradle-android-emulator#244]
Where can I find the documantation on how to work with this plugin? 
How do I start created emulator? 
Where can I find description and options of various tasks created by this plugin?

**Comment by ParohyGr** [comment]
So all I have to do is run `app:connectedAndroidTest` and it will start up the emulator in `avdRoot` ?

**Comment by ParohyGr** [comment]
It is working as you described it. One question though: How do you view diff files which are stored on the device when test fails? Is there a gradle task for it in this plug in as well?

**Comment by quittle** [comment]
This plugin doesn't pull any specific files off the device, though the Android Gradle Plugin may pull some files as part of running instrumentation tests.

There is an open issue #196 to add support so you can run custom actions. There is a good amount of discussion and code snippets in #193 that should unblock you write what you need to pull extra files off the emulator after the tests run and before the emulator shuts down.

**Comment by ParohyGr** [comment]
Thank you for your help 🚀 ! Much appreciate it! Have a nice weekend ✌️
