### ISSUE TITLE
Plugin does not handle already connected device/emulator gracefully

### ISSUE THREAD

**Issue by quittle** [quittle/gradle-android-emulator#35]
The plugin should be able to handle an already connected device by specifying the emulator to issue commands to instead of failing with an error that multiple devices were connected

**Comment by skjolber** [comment]
@quittle Hi, any progress on this? I guess it would involve setting `ANDROID_SERIAL` somehow.

**Comment by quittle** [comment]
Hey, I haven't looked into it in quite a while. The problem I have is being able to guess the emulator's reported name prior to starting it. Even if this plugin didn't fail, it would still have to update the Android connected test target to run on the specific emulator started by the plugin. Has this become an issue for your development?

**Comment by skjolber** [comment]
So is the emulator name a function of the port it runs on? Perhaps by explicitly adding a port number (e.g. `-port 5556`), the resulting name can be predicted? 

So in other words, first find a free port, then append `additionalEmulatorArguments` and predict the emulator name, passing it via `ANDROID_SERIAL` (or some other means). 

And/or a workaround could be a small bash script setting the `ANDROID_SERIAL` environment variable (using the same plan).

**Comment by quittle** [comment]
I've found [this StackOverflow answer](https://stackoverflow.com/a/42038655/1554990) which looks very promising for consistently detecting the correct emulator and am working on implementing that. I still need to investigate further on how I can automate restricting the instrumentation tests to run on this specific emulator but will see what I can do.

**Comment by quittle** [comment]
As I work on this in my spare time, it's hard to get things done but I've got an implementation I'm happy with that fixes this and works fairly well while remaining flexible. I will hopefully clean it up and land the change tomorrow and release the new version by Thursday. No promises though.

**Comment by quittle** [comment]
It seems that I cannot use `emu.uuid` to detect an emulator started anymore. This broke in the [August release of the emulator](https://developer.android.com/studio/releases/emulator#30-0-26). I will switch to doing the port trick where I find an open emulator port and request it specifically. The odd thing is that it worked locally on x86 emulators.

It'll take a little more time to get this completed.

**Comment by quittle** [comment]
Okay, released as version `0.4.1` of the plugin. Try it out and let me know how it goes.

**Comment by quittle** [comment]
@skjolber, can you confirm if the new release works for you with multiple devices?
