### ISSUE TITLE
build-tools path is wrong with Command line tools only official archive

### ISSUE THREAD

**Issue by ptsneves** [quittle/gradle-android-emulator#84]
https://github.com/quittle/gradle-android-emulator/blob/dbd0844b7fd6abe69bce2057dafe0ae7661b51e9/android-emulator-plugin/src/main/java/com/quittle/androidemulator/EmulatorConfiguration.java#L110

When you download for example [Command line tools only](https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip) the path should be
`return sdkFile(sdkRoot,"cmdline-tools", "tools", "bin", "sdkmanager"); `
The same for avd path.

If you required it, i can submit a pull request, but i am not sure if i am not doing something wrong.

**Comment by quittle** [comment]
**Hmm, could you provide the error and stacktrace you get when running using the command-line only tools?**

Double-checking the code, if you are able to build your app (e.g. `./gradlew assemble`) with your `ANDROID_SDK_ROOT` or `ANDROID_SDK_HOME` set up, then this plugin should be re-using the same SDK root.

If you look at the `installSdkDependenciesForAndroidEmulatorPlugin` task, it should explicitly install the `cmdline-tools;lastest` package and use that to install further dependencies using `getSdkManager()`, not `getCmdLineToolsSdkManager()`, which you linked to.

https://github.com/quittle/gradle-android-emulator/blob/a353ba97c16149bca55fc5f16e2a23ba0c9696d8/android-emulator-plugin/src/main/java/com/quittle/androidemulator/AndroidEmulatorPlugin.java#L132-L151

`getSdkManager()` looks like it should work if you set your SDK_ROOT to be the `cmdline-tools` folder.

https://github.com/quittle/gradle-android-emulator/blob/a353ba97c16149bca55fc5f16e2a23ba0c9696d8/android-emulator-plugin/src/main/java/com/quittle/androidemulator/EmulatorConfiguration.java#L98-L104

The method you linked to in the description is for `getCmdLineToolsSdkManager()`, which won't be available until after the `sdkmanager` you provide installs the newer `sdkmanager`.

**Comment by quittle** [comment]
@ptsneves could you provide the info requested in my comment above?

**Comment by ptsneves** [comment]
@quittle  sorry for the delay. Actually from your explanation it seems I severely misunderstood how to use this project. My goal was to use it inside a docker with pre populated tools so the sdkmanager would not need to redownload for certain project configurations:
```
#docker file that sets up environment
FROM ubuntu:focal

USER root

ENV ANDROID_HOME=/android-sdk-linux \
    LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8 \
    LANGUAGE=en_US:en

ENV ANDROID_SDK_ROOT=$ANDROID_HOME \
    PATH=${PATH}:${ANDROID_HOME}/cmdline-tools/tools/bin:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/emulator

ENV ANDROID_SDK_TOOLS_VERSION=6609375 \
    BUILDTOOLS_VERSION=29.0.3 \
    PLATFORM_VERSION=30

RUN set -o xtrace \
    && cd /opt \
    && apt-get update \
    && apt-get install -y openjdk-8-jdk wget unzip zip \
    && rm -rf /var/lib/apt/lists/* \
    &&  wget -q https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS_VERSION}_latest.zip -O android-sdk-tools.zip \
    && mkdir -p ${ANDROID_HOME}/cmdline-tools/ \
    && unzip -q android-sdk-tools.zip -d ${ANDROID_HOME}/cmdline-tools/ \
    && ln -sf ${ANDROID_HOME}/cmdline-tools/tools ${ANDROID_HOME}/cmdline-tools/latest \
    && chown -R root:root $ANDROID_HOME \
    && rm android-sdk-tools.zip \
    && echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers \
    && yes | sdkmanager --licenses \
    && touch /root/.android/repositories.cfg \
    && sdkmanager platform-tools emulator "platforms;android-${PLATFORM_VERSION}" "build-tools;${BUILDTOOLS_VERSION}" "system-images;android-${PLATFORM_VERSION};google_apis;x86_64" \
    && mkdir -p /root/.android \
    && touch /root/.android/repositories.cfg

ENV APP_PATH="app" \
    HOME="/tmp/workdir"

COPY ./entrypoint.sh /usr/bin/entrypoint
RUN chmod 755 /usr/bin/entrypoint
RUN chmod 777 -R ${ANDROID_HOME}
ENTRYPOINT [ "entrypoint" ]
```

Entry point program
```
#!/usr/bin/env bash
set -eux

if [ -z ${CODE_DIR} ]; then
    >&2 echo "Error: Please specify CODE_DIR as an environmental variable. This is where the drohub code should be available at"
    exit 1
fi

if [ -z ${APP_PATH} ]; then
    >&2 echo "Error: Please specify APP_PATH as an environmental variable. This is where the drohub code should be available at"
    exit 1
fi

mkdir -p ${HOME}
cp -a ${CODE_DIR}/${APP_PATH} ${HOME}/
pushd ${HOME}/${APP_PATH}/android/
rm -rf app/build
./gradlew --gradle-user-home ${CODE_DIR}/${APP_PATH}/android/docker-gradle-home/ connectedDebugAndroidTest
```

build.gradle
```
apply plugin: 'com.android.application'
apply plugin: 'com.quittle.android-emulator'
[...]

androidEmulator {
    emulator {
        name 'my_avd_emulator_name' // Defaults to be dynamically based on the configuration of the AVD
        device 'pixel_xl' // Defaults to exclude the device flag, using avdmanager default. For options, run avdmanager list device
        sdkVersion 30 // Defaults to (Target SDK), then (Min SDK), then finally 10
        abi 'x86_64' // Defaults to x86
        includeGoogleApis true // Defaults to false
    }

    enableForAndroidTests true // Defaults to true
    headless true // Defaults to false but should be set to true for most CI systems
//    additionalEmulatorArguments '-no-snapshot', '-http-proxy=localhost:1234' // Additional arguments to pass to the emulator at startup. See https://developer.android.com/studio/run/emulator-commandline#startup-options for options
    logEmulatorOutput true // Defaults to false but can be enabled to have emulator output logged for debugging.
}
[...]
```

In the dockerfile the `&& ln -sf ${ANDROID_HOME}/cmdline-tools/tools ${ANDROID_HOME}/cmdline-tools/latest \` was the adaptation i needed to do which i am speaking about.

Do you think this kind of Dockerfile approach is suitable for gradle-android-emulator?

**Comment by quittle** [comment]
Hmm, well the plugin was certainly intended for networked environments to make getting it all set up easy but I don't see why we can't update it to support your use-case. I see two potential paths forward

1. If you install all the dependencies the plugin tries to install when building your image, including `cmdline-tools;latest`, `emulator`, and the emulator system image you intend to use, then it shouldn't need to make any network calls. There's a decent chance that when you perform the build, the installation tasks will be marked as UP-TO-DATE by Gradle as you made the files it looks for already available and that even if `sdkmanager` does run, it should without network as nothing will need to be installed.

2. If that doesn't work, you can try explicitly disabling the `installSdkDependenciesForAndroidEmulatorPlugin` and `installAndroidEmulatorSystemImageForAndroidEmulatorPlugin` tasks with
```groovy
afterEvaluate {
    tasks["installSdkDependenciesForAndroidEmulatorPlugin"].enabled = false
    tasks["installAndroidEmulatorSystemImageForAndroidEmulatorPlugin"].enabled = false
}
```
after applying the plugin. It then shouldn't attempt to install anything and hopefully will "just work" with the dependencies you installed ahead of time.

If either of these methods works for you, I'd be happy to take any pull requests that make the configuration simpler for you. Perhaps an `installDependencies`  configuration that you can disable would be appropriate for disabling the tasks if that's all it takes. It could then log what dependencies it expects to already be available.

**Comment by ptsneves** [comment]
Hey @quittle 

Thanks for the thorough answer. I ended up using a different approach for the networked issue(more below). It was possible because now i understand correctly the plugin's philosophy of getting everything ready in the gradle build system.

In my previous approach the cached results were in the docker image itself, and this required maintenance of the alignment of the docker image and the build.gradle in sync.

Now I completely let the gradle plugin run the show, albeit in a directory that is persisted in the user mounted core repo. This way different docker/gradlew runs just have access to same directory structure that was already pre-populated in other runs. We can call this form of caching runtime while the previous caching in the build image, it was static.

There is still the issue of networking if the runtime cache mentioned is not yet primed but this is easily worked around with very simple archival of such caches if required. On a developer case, he/she just needs to pay the penalty once. For the CI it can just fetch this archive from wherever it wants and re-upload it if necessary for later re-runs.

I ended up with a very simple Dockerfile to run this gradle plugin. The runtime-cache is basically `.docker-android-home'`

```Dockerfile
FROM ubuntu:focal

USER root

RUN set -o xtrace \
    && apt-get update \
    && apt-get install -y openjdk-8-jdk wget unzip zip sudo \
    && echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

ENV APP_PATH="my_app_path_in_container" \
    LICENSES_PATH="/usr/share/android/licenses"

COPY ./entrypoint.sh /usr/bin/entrypoint
RUN chmod 755 /usr/bin/entrypoint \
    && mkdir -p ${LICENSES_PATH}

#Assumed that you have your licenses in the container build contextex.
COPY licenses/android-sdk-license ${LICENSES_PATH}/
ENTRYPOINT [ "entrypoint" ]
```

```bash
#!/usr/bin/env bash
set -eux

if [ -z ${CODE_DIR} ]; then
    >&2 echo "Error: Please specify CODE_DIR as an environmental variable. This is where the code should be available at"
    exit 1
fi

if [ -z ${APP_PATH} ]; then
    >&2 echo "Error: Please specify APP_PATH as an environmental variable. This is where the app code should be available at relative to the code dir. This is to avoid copying more than the app"
    exit 1
fi

#required for QEMU emulator
if [ ! -w /dev/kvm ]; then
    >&2 echo "Error: kvm is not writable"
    exit 1
fi

export REAL_APP_PATH="${CODE_DIR}/${APP_PATH}"
export HOME=${CODE_DIR}/.docker-android-home
export GRADLE_HOME="${HOME}/gradle-home"
export ANDROID_SDK_ROOT=${HOME}
export ANDROID_HOME=${HOME}

mkdir -p ${HOME}
cp -a ${LICENSES_PATH} ${HOME}

cp -a ${REAL_APP_PATH} ${ANDROID_HOME}/
pushd ${ANDROID_HOME}/${APP_PATH}/android/
rm -rf app/build
#Notice that we can pass extra parameters to our docker container as COMMAND. Useful to pass system arguments to instrumented tests
./gradlew --gradle-user-home ${GRADLE_HOME} connectedDebugAndroidTest $@
```

I am closing the ticket because my original complaint does not make much sense :). Regarding the PR, I think it is actually not needed. Your system is very good, and does what it promises, it is my fault for not understanding it. At most I think i could improve the docs as I found that it only describes the :app build.gradle and not the top level build.gradle specifically that `classpath "com.quittle:android-emulator-plugin:0.3.0"` needs to be added to the dependencies :)

**Comment by neworld** [comment]
I have a very similar problem, but I believe the problem could be on my side. I was updating the docker image to use JDK11 with the latest SDK tools. However, I got an error:

```
com.android.sdklib.tool.sdkmanager.SdkManagerCliSettings.<init>(SdkManagerCliSettings.java:428)
```

Some sources on [StackOverflow](https://stackoverflow.com/questions/60440509/android-command-line-tools-sdkmanager-always-shows-warning-could-not-create-se) and other explained that tools must be added into `cmdline-tools`, so path became  `cmdline-tools/tools/bin/sdkmanager`. It also means, I do not have `tools/bin/sdkmanager at all`. It just does not exist. 

So, this plugin [will crash[(https://github.com/quittle/gradle-android-emulator/blob/99bce31e4a252620b3ce15df8eed67f390f7626d/android-emulator-plugin/src/main/java/com/quittle/androidemulator/AndroidEmulatorPlugin.java#L92-L94) because `tools/bin/sdkmanager` does not exist anymore. Also, it expects to find sdkmanager on different folder:

```diff
-cmdline-tools/tools/bin/sdkmanager
+cmdline-tools/latest/bin/sdkmanager
```

But I tried to disable check tasks, but then I got:
```
Caused by: org.gradle.process.internal.ExecException: A problem occurred starting process 'command '/opt/android-sdk/tools/bin/sdkmanager''
        at org.gradle.process.internal.DefaultExecHandle.execExceptionFor(DefaultExecHandle.java:241)
        at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:218)
        at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:369)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:87)
        at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: net.rubygrapefruit.platform.NativeException: Could not start '/opt/android-sdk/tools/bin/sdkmanager'
        at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
        at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
        at org.gradle.process.internal.ExecHandleRunner.startProcess(ExecHandleRunner.java:98)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:71)
        ... 4 more
Caused by: java.io.IOException: Cannot run program "/opt/android-sdk/tools/bin/sdkmanager" (in directory "/opt/build/application"): error=2, No such file or directory
        at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
        ... 7 more
Caused by: java.io.IOException: error=2, No such file or directory
        ... 8 more
```

The only way I managed to make builds success is:

- create link in the image: `&& ln -sf ${ANDROID_HOME}/cmdline-tools/tools ${ANDROID_HOME}/cmdline-tools/latest \`
- Disable some tasks:
```
afterEvaluate {
    tasks["ensureBaseSdkPermissionsForAndroidEmulatorPlugin"].enabled = false
    tasks["installSdkDependenciesForAndroidEmulatorPlugin"].enabled = false
}
```

However, I believe the main usage of this plugin is CI. Developers have a play button in the IDE. Would be nice if the plugin will be more robust or provide good practices on how to build images.

**Comment by quittle** [comment]
@ptsneves, you said the following

> At most I think i could improve the docs as I found that it only describes the :app build.gradle and not the top level build.gradle specifically that classpath "com.quittle:android-emulator-plugin:0.3.0" needs to be added to the dependencies :)

What instructions were you following to get set up and where did you get lost? The plugin is published on [plugins.gradle.org](https://plugins.gradle.org/plugin/com.quittle.android-emulator) you should be able to take the dependency on it with just the following code in the same `build.gradle` as you apply the android plugin.

```groovy
plugins {
    id 'com.quittle.android-emulator' version '0.3.0'
}
```

If that doesn't work, I'll take another look into how it affects multi-project repositories and provide better documentation.

**Comment by neworld** [comment]
I like the first approach of having multiple checks. I really like your suggestion. Maybe I would use `cmdline-tools/tools/bin/sdkmanager` instead `cmdline-tools/*/bin/sdkmanager`, because `tools` is a folder described in multiple sources. And AGP is workinging perfectly with it. 

Exposing a field may be useful for people who do have non-standard installations. But I believe it is very unlikely because AGP is expecting some proper structure.

> Finally, do you have any concerns with this plugin performing the installation and thus having a network dependency?

I do not have. But maybe a good idea to let people choose if they prefer the latest installation of the tools.

**Comment by neworld** [comment]
I was reading AGP code and found that `com.android.tools:sdklib` is used for SDK management (gathering the latest build tools, installing missing dependencies, checking licenses). But I can't find any algorithm how `sdkmanager` location is determined. Maybe `sdkmanager` is just a CLI wrapper of this sdklib. Just an idea, but maybe sdklib could be reused in this plugin as well?

**Comment by quittle** [comment]
@neworld @ptsneves does the above commit look like it should address the issues you were having? If so, I'll publish a new version of the plugin.

**Comment by neworld** [comment]
It looks great to me. Can't wait to try.

**Comment by quittle** [comment]
Okay, I've released it in v0.4.0 of the plugin. Try it out and let me know if it works for you.

**Comment by quittle** [comment]
@neworld @ptneves, have you had a chance to try out 0.4.0 of the plugin yet to confirm if it fixes your problems?

**Comment by neworld** [comment]
The new version works just perfectly.

**Comment by ptsneves** [comment]
Hello @quittle, sorry for my late answer, and i blush slightly at my lack of courtesy towards your efforts :(. My apologies

Regarding the instructions I found that in my Android build.gradle I needed to add the maven repository as well as dependencies to the classpath. I made some tests and found that without these, the project does not build. See comments below:

```

buildscript {
    repositories {
        google()
        jcenter()
        maven { //I needed to add maven. The default Android Studio templates do not have the maven repo enabled
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.0.0'
        classpath "com.quittle:android-emulator-plugin:0.3.0" // I needed to add this line to get the emulator in the classpath to be used by the app's build.gradle
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

Another point, when trying to upgrade from 0.3.0 to 0.4.0 I found out that the minimum gradle version is 6.5. There is no mention of it in the documentation. 

In the end I failed to upgrade and try 0.4.0 as it seems to require gradle 6.5 which in turn requires android gradle plugin 4.1 which in turn is not compatible with Intelj, which is what i use https://youtrack.jetbrains.com/issue/IDEA-252775.

Grateful for the effort

**Comment by quittle** [comment]
Hey @ptsneves, for your first issue around consuming the plugin. I was confused how I published the plugin and assumed it was being published to Maven Central but apparently it's only via the Gradle plugin repo so I've created https://github.com/quittle/gradle-android-emulator/issues/88 to track publishing to built-in maven repos.

For the second, my plugin doesn't require a minimum Gradle version or Android Gradle plugin explicitly. You can see on the [Android Gradle plugin release page](https://developer.android.com/studio/releases/gradle-plugin#updating-gradle) that version 4.1+ requires Gradle 6.5+ and prints a warning message, which is likely what you saw. As you can [see as part of my tests](https://github.com/quittle/gradle-android-emulator/blob/master/validate_plugin#L63) this plugin actually supports all the way back to version 2.3.3 of the Android plugin. Try downgrading the version of the Android Gradle plugin your project depends on back to what works and keep the Gradle version you already had. If you're still having issues, please open a new issue so we can track it separately from this one, which has seemingly been fixed (if you could the plugin to work). If 0.4.0 fails to support your command line tools, feel free to re-open,
